#ifndef TARGET_OS_SIMULATOR
#include <TargetConditionals.h>
#endif
#if TARGET_OS_SIMULATOR
#if 0
#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.0.1 effective-4.2 (swiftlang-1001.0.82.4 clang-1001.0.46.5)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="RealTime",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

enum TRTBoardType : NSInteger;
@class TRTStation;
@class TRTBoardService;
@class TRTDisruption;

SWIFT_CLASS_NAMED("Board")
@interface TRTBoard : NSObject
@property (nonatomic, readonly) enum TRTBoardType type;
@property (nonatomic, readonly, strong) TRTStation * _Nonnull station;
@property (nonatomic, readonly, copy) NSArray<TRTBoardService *> * _Nonnull services;
@property (nonatomic, readonly, copy) NSDate * _Nonnull lastUpdate;
@property (nonatomic, readonly) BOOL darwinDataFeedAvailable;
@property (nonatomic, readonly, copy) NSURL * _Nonnull earlierServicesURL;
@property (nonatomic, readonly, copy) NSURL * _Nonnull laterServicesURL;
@property (nonatomic, readonly, copy) NSArray<TRTDisruption *> * _Nullable disruptions;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



@protocol TRTBoardRequestParameters;
@class NSURLSessionDataTask;

SWIFT_CLASS_NAMED("BoardRequest")
@interface TRTBoardRequest : NSObject
- (nonnull instancetype)initWithBaseURL:(NSURL * _Nonnull)baseURL parameters:(id <TRTBoardRequestParameters> _Nonnull)parameters OBJC_DESIGNATED_INITIALIZER;
- (NSURLSessionDataTask * _Nonnull)fetchBoardWithCompletion:(void (^ _Nonnull)(TRTBoard * _Nullable, NSError * _Nullable))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL_NAMED("BoardRequestParameters")
@protocol TRTBoardRequestParameters
@property (nonatomic, readonly) enum TRTBoardType type;
@property (nonatomic, readonly, strong) TRTStation * _Nonnull station;
- (NSURL * _Nonnull)urlWithPreferredBaseURL:(NSURL * _Nonnull)preferredBaseURL SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS_NAMED("BoardRequestExplicitParameters")
@interface TRTBoardRequestExplicitParameters : NSObject <TRTBoardRequestParameters>
@property (nonatomic, readonly) enum TRTBoardType type;
@property (nonatomic, readonly, strong) TRTStation * _Nonnull station;
- (nonnull instancetype)initWithType:(enum TRTBoardType)type station:(TRTStation * _Nonnull)station stopAtStation:(TRTStation * _Nullable)stopAtStation time:(NSDate * _Nullable)time OBJC_DESIGNATED_INITIALIZER;
- (NSURL * _Nonnull)urlWithPreferredBaseURL:(NSURL * _Nonnull)preferredBaseURL SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("BoardRequestImplicitParameters")
@interface TRTBoardRequestImplicitParameters : NSObject <TRTBoardRequestParameters>
@property (nonatomic, readonly) enum TRTBoardType type;
@property (nonatomic, readonly, strong) TRTStation * _Nonnull station;
- (nonnull instancetype)initWithType:(enum TRTBoardType)type station:(TRTStation * _Nonnull)station url:(NSURL * _Nonnull)url OBJC_DESIGNATED_INITIALIZER;
- (NSURL * _Nonnull)urlWithPreferredBaseURL:(NSURL * _Nonnull)preferredBaseURL SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


enum TRTCallingType : NSInteger;
@class TRTBoardingInformation;
@class TRTStopAtInformation;
enum TRTStatusType : NSInteger;

SWIFT_CLASS_NAMED("BoardService")
@interface TRTBoardService : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull identifier;
@property (nonatomic, readonly, copy) NSString * _Nonnull serviceOperator;
@property (nonatomic, readonly, copy) NSString * _Nonnull transportMode;
@property (nonatomic, readonly) enum TRTCallingType callingType;
@property (nonatomic, readonly, copy) NSArray<TRTStation *> * _Nonnull stations;
@property (nonatomic, readonly, copy) NSString * _Nullable via;
@property (nonatomic, readonly, strong) TRTBoardingInformation * _Nonnull boardingInformation;
@property (nonatomic, readonly, strong) TRTStopAtInformation * _Nullable stopAtInformation;
@property (nonatomic, readonly, copy) NSURL * _Nonnull tripURL;
@property (nonatomic, readonly) BOOL circularRoute;
@property (nonatomic, readonly) BOOL splits;
@property (nonatomic, readonly) BOOL joins;
@property (nonatomic, readonly) enum TRTStatusType status;
@property (nonatomic, readonly, copy) NSString * _Nullable disruptionCode;
@property (nonatomic, readonly, copy) NSString * _Nullable disruptionReason;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




@interface TRTBoardService (SWIFT_EXTENSION(RealTime))
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) NSUInteger hash;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, TRTBoardType, "BoardType", closed) {
  TRTBoardTypeDepartures = 0,
  TRTBoardTypeArrivals = 1,
};

@class TRTScheduledInformation;
@class TRTRealTimeInformation;

SWIFT_CLASS_NAMED("BoardingInformation")
@interface TRTBoardingInformation : NSObject
@property (nonatomic, readonly, strong) TRTScheduledInformation * _Nullable scheduled;
@property (nonatomic, strong) TRTRealTimeInformation * _Nullable realTime;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



typedef SWIFT_ENUM_NAMED(NSInteger, TRTCallingType, "CallingType", closed) {
  TRTCallingTypePickUp = 0,
  TRTCallingTypeNormal = 1,
  TRTCallingTypePassing = 2,
  TRTCallingTypeSetDown = 3,
  TRTCallingTypeRequest = 4,
};




SWIFT_CLASS_NAMED("Disruption")
@interface TRTDisruption : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull category;
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
@property (nonatomic, readonly, copy) NSString * _Nonnull severity;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



typedef SWIFT_ENUM_NAMED(NSInteger, TRTErrorCode, "ErrorCode", closed) {
  TRTErrorCodeUnknown = 0,
  TRTErrorCodeInvalidRequest = 1,
  TRTErrorCodeInvalidResponse = 2,
  TRTErrorCodeInternalError = 3,
  TRTErrorCodeNotFound = 4,
  TRTErrorCodeRequestTimedOut = 5,
  TRTErrorCodeInvalidParameter = 6,
  TRTErrorCodeInvalidParameterValue = 7,
};



typedef SWIFT_ENUM_NAMED(NSInteger, TRTProjection, "Projection", closed) {
  TRTProjectionNone = 0,
  TRTProjectionEstimated = 1,
  TRTProjectionActual = 2,
  TRTProjectionDelayed = 3,
};

@class TRTStatus;

SWIFT_CLASS_NAMED("RealTimeInformation")
@interface TRTRealTimeInformation : NSObject
@property (nonatomic, readonly, copy) NSDate * _Nullable time;
@property (nonatomic, readonly, copy) NSString * _Nullable platform;
@property (nonatomic, readonly) enum TRTProjection projection;
@property (nonatomic, readonly, strong) TRTStatus * _Nonnull status;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




SWIFT_CLASS_NAMED("ScheduledInformation")
@interface TRTScheduledInformation : NSObject
@property (nonatomic, readonly, copy) NSDate * _Nullable time;
@property (nonatomic, readonly, copy) NSString * _Nullable platform;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




SWIFT_CLASS_NAMED("Station")
@interface TRTStation : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull crsCode;
- (nonnull instancetype)initWithCrsCode:(NSString * _Nonnull)crsCode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




SWIFT_CLASS_NAMED("Status")
@interface TRTStatus : NSObject
@property (nonatomic, readonly) enum TRTStatusType type;
@property (nonatomic, readonly) BOOL arrived;
@property (nonatomic, readonly) BOOL departed;
@property (nonatomic, readonly, copy) NSString * _Nullable disruptionCode;
@property (nonatomic, readonly, copy) NSString * _Nullable disruptionReason;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



typedef SWIFT_ENUM_NAMED(NSInteger, TRTStatusType, "StatusType", closed) {
  TRTStatusTypeOnTime = 0,
  TRTStatusTypeDelayed = 1,
  TRTStatusTypeCancelled = 2,
};

@class TRTTripService;

SWIFT_CLASS_NAMED("Stop")
@interface TRTStop : NSObject
@property (nonatomic, readonly) enum TRTCallingType callingType;
@property (nonatomic, readonly, strong) TRTStation * _Nonnull station;
@property (nonatomic, readonly, strong) TRTBoardingInformation * _Nullable arrival;
@property (nonatomic, readonly, strong) TRTBoardingInformation * _Nullable departure;
@property (nonatomic, readonly, copy) NSArray<TRTTripService *> * _Nullable associatedServices;
@property (nonatomic) BOOL lastDepartedStop;
@property (nonatomic) BOOL nextArrivalStop;
@property (nonatomic) BOOL serviceAtDestination;
@property (nonatomic) BOOL serviceAtOrigin;
@property (nonatomic) BOOL serviceAtStop;
@property (nonatomic, readonly) enum TRTStatusType status;
@property (nonatomic, readonly, copy) NSString * _Nullable disruptionCode;
@property (nonatomic, readonly, copy) NSString * _Nullable disruptionReason;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




@interface TRTStop (SWIFT_EXTENSION(RealTime)) <NSCopying>
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS_NAMED("StopAtInformation")
@interface TRTStopAtInformation : NSObject
@property (nonatomic, readonly) enum TRTCallingType callingType;
@property (nonatomic, readonly, strong) TRTBoardingInformation * _Nullable boardingInformation;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




SWIFT_CLASS_NAMED("Trip")
@interface TRTTrip : NSObject
@property (nonatomic, readonly, strong) TRTTripService * _Nonnull service;
@property (nonatomic, readonly) BOOL darwinDataFeedAvailable;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



@protocol TRTTripRequestParameters;

SWIFT_CLASS_NAMED("TripRequest")
@interface TRTTripRequest : NSObject
- (nonnull instancetype)initWithBaseURL:(NSURL * _Nonnull)baseURL parameters:(id <TRTTripRequestParameters> _Nonnull)parameters OBJC_DESIGNATED_INITIALIZER;
- (NSURLSessionDataTask * _Nonnull)fetchTripWithCompletion:(void (^ _Nonnull)(TRTTrip * _Nullable, NSError * _Nullable))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL_NAMED("TripRequestParameters")
@protocol TRTTripRequestParameters
- (NSURL * _Nonnull)urlWithPreferredBaseURL:(NSURL * _Nonnull)preferredBaseURL SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS_NAMED("TripRequestExplicitParameters")
@interface TRTTripRequestExplicitParameters : NSObject <TRTTripRequestParameters>
@property (nonatomic, readonly, copy) NSString * _Nonnull trainIdentifier;
@property (nonatomic, readonly, copy) NSDate * _Nonnull date;
- (nonnull instancetype)initWithTrainIdentifier:(NSString * _Nonnull)trainIdentifier date:(NSDate * _Nonnull)date OBJC_DESIGNATED_INITIALIZER;
- (NSURL * _Nonnull)urlWithPreferredBaseURL:(NSURL * _Nonnull)preferredBaseURL SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("TripRequestImplicitParameters")
@interface TRTTripRequestImplicitParameters : NSObject <TRTTripRequestParameters>
@property (nonatomic, readonly, copy) NSURL * _Nonnull url;
- (nonnull instancetype)initWithUrl:(NSURL * _Nonnull)url OBJC_DESIGNATED_INITIALIZER;
- (NSURL * _Nonnull)urlWithPreferredBaseURL:(NSURL * _Nonnull)preferredBaseURL SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


enum TRTTripServiceAssociation : NSInteger;

SWIFT_CLASS_NAMED("TripService")
@interface TRTTripService : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull serviceOperator;
@property (nonatomic, readonly, copy) NSString * _Nonnull transportMode;
@property (nonatomic, readonly) BOOL replacementBus;
@property (nonatomic, readonly, copy) NSArray<TRTStop *> * _Nonnull stops;
@property (nonatomic, readonly) enum TRTTripServiceAssociation association;
@property (nonatomic) enum TRTTripServiceAssociation detectedAssociation;
@property (nonatomic, copy) NSArray<TRTStop *> * _Nullable commonStops;
@property (nonatomic, copy) NSArray<TRTStop *> * _Nullable leftLegStops;
@property (nonatomic, copy) NSArray<TRTStop *> * _Nullable rightLegStops;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



typedef SWIFT_ENUM_NAMED(NSInteger, TRTTripServiceAssociation, "TripServiceAssociation", closed) {
  TRTTripServiceAssociationNone = 0,
  TRTTripServiceAssociationSplit = 1,
  TRTTripServiceAssociationJoin = 2,
};

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#elif defined(__i386__) && __i386__
// Generated by Apple Swift version 5.0.1 effective-4.2 (swiftlang-1001.0.82.4 clang-1001.0.46.5)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="RealTime",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

enum TRTBoardType : NSInteger;
@class TRTStation;
@class TRTBoardService;
@class TRTDisruption;

SWIFT_CLASS_NAMED("Board")
@interface TRTBoard : NSObject
@property (nonatomic, readonly) enum TRTBoardType type;
@property (nonatomic, readonly, strong) TRTStation * _Nonnull station;
@property (nonatomic, readonly, copy) NSArray<TRTBoardService *> * _Nonnull services;
@property (nonatomic, readonly, copy) NSDate * _Nonnull lastUpdate;
@property (nonatomic, readonly) BOOL darwinDataFeedAvailable;
@property (nonatomic, readonly, copy) NSURL * _Nonnull earlierServicesURL;
@property (nonatomic, readonly, copy) NSURL * _Nonnull laterServicesURL;
@property (nonatomic, readonly, copy) NSArray<TRTDisruption *> * _Nullable disruptions;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



@protocol TRTBoardRequestParameters;
@class NSURLSessionDataTask;

SWIFT_CLASS_NAMED("BoardRequest")
@interface TRTBoardRequest : NSObject
- (nonnull instancetype)initWithBaseURL:(NSURL * _Nonnull)baseURL parameters:(id <TRTBoardRequestParameters> _Nonnull)parameters OBJC_DESIGNATED_INITIALIZER;
- (NSURLSessionDataTask * _Nonnull)fetchBoardWithCompletion:(void (^ _Nonnull)(TRTBoard * _Nullable, NSError * _Nullable))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL_NAMED("BoardRequestParameters")
@protocol TRTBoardRequestParameters
@property (nonatomic, readonly) enum TRTBoardType type;
@property (nonatomic, readonly, strong) TRTStation * _Nonnull station;
- (NSURL * _Nonnull)urlWithPreferredBaseURL:(NSURL * _Nonnull)preferredBaseURL SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS_NAMED("BoardRequestExplicitParameters")
@interface TRTBoardRequestExplicitParameters : NSObject <TRTBoardRequestParameters>
@property (nonatomic, readonly) enum TRTBoardType type;
@property (nonatomic, readonly, strong) TRTStation * _Nonnull station;
- (nonnull instancetype)initWithType:(enum TRTBoardType)type station:(TRTStation * _Nonnull)station stopAtStation:(TRTStation * _Nullable)stopAtStation time:(NSDate * _Nullable)time OBJC_DESIGNATED_INITIALIZER;
- (NSURL * _Nonnull)urlWithPreferredBaseURL:(NSURL * _Nonnull)preferredBaseURL SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("BoardRequestImplicitParameters")
@interface TRTBoardRequestImplicitParameters : NSObject <TRTBoardRequestParameters>
@property (nonatomic, readonly) enum TRTBoardType type;
@property (nonatomic, readonly, strong) TRTStation * _Nonnull station;
- (nonnull instancetype)initWithType:(enum TRTBoardType)type station:(TRTStation * _Nonnull)station url:(NSURL * _Nonnull)url OBJC_DESIGNATED_INITIALIZER;
- (NSURL * _Nonnull)urlWithPreferredBaseURL:(NSURL * _Nonnull)preferredBaseURL SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


enum TRTCallingType : NSInteger;
@class TRTBoardingInformation;
@class TRTStopAtInformation;
enum TRTStatusType : NSInteger;

SWIFT_CLASS_NAMED("BoardService")
@interface TRTBoardService : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull identifier;
@property (nonatomic, readonly, copy) NSString * _Nonnull serviceOperator;
@property (nonatomic, readonly, copy) NSString * _Nonnull transportMode;
@property (nonatomic, readonly) enum TRTCallingType callingType;
@property (nonatomic, readonly, copy) NSArray<TRTStation *> * _Nonnull stations;
@property (nonatomic, readonly, copy) NSString * _Nullable via;
@property (nonatomic, readonly, strong) TRTBoardingInformation * _Nonnull boardingInformation;
@property (nonatomic, readonly, strong) TRTStopAtInformation * _Nullable stopAtInformation;
@property (nonatomic, readonly, copy) NSURL * _Nonnull tripURL;
@property (nonatomic, readonly) BOOL circularRoute;
@property (nonatomic, readonly) BOOL splits;
@property (nonatomic, readonly) BOOL joins;
@property (nonatomic, readonly) enum TRTStatusType status;
@property (nonatomic, readonly, copy) NSString * _Nullable disruptionCode;
@property (nonatomic, readonly, copy) NSString * _Nullable disruptionReason;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




@interface TRTBoardService (SWIFT_EXTENSION(RealTime))
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) NSUInteger hash;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, TRTBoardType, "BoardType", closed) {
  TRTBoardTypeDepartures = 0,
  TRTBoardTypeArrivals = 1,
};

@class TRTScheduledInformation;
@class TRTRealTimeInformation;

SWIFT_CLASS_NAMED("BoardingInformation")
@interface TRTBoardingInformation : NSObject
@property (nonatomic, readonly, strong) TRTScheduledInformation * _Nullable scheduled;
@property (nonatomic, strong) TRTRealTimeInformation * _Nullable realTime;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



typedef SWIFT_ENUM_NAMED(NSInteger, TRTCallingType, "CallingType", closed) {
  TRTCallingTypePickUp = 0,
  TRTCallingTypeNormal = 1,
  TRTCallingTypePassing = 2,
  TRTCallingTypeSetDown = 3,
  TRTCallingTypeRequest = 4,
};




SWIFT_CLASS_NAMED("Disruption")
@interface TRTDisruption : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull category;
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
@property (nonatomic, readonly, copy) NSString * _Nonnull severity;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



typedef SWIFT_ENUM_NAMED(NSInteger, TRTErrorCode, "ErrorCode", closed) {
  TRTErrorCodeUnknown = 0,
  TRTErrorCodeInvalidRequest = 1,
  TRTErrorCodeInvalidResponse = 2,
  TRTErrorCodeInternalError = 3,
  TRTErrorCodeNotFound = 4,
  TRTErrorCodeRequestTimedOut = 5,
  TRTErrorCodeInvalidParameter = 6,
  TRTErrorCodeInvalidParameterValue = 7,
};



typedef SWIFT_ENUM_NAMED(NSInteger, TRTProjection, "Projection", closed) {
  TRTProjectionNone = 0,
  TRTProjectionEstimated = 1,
  TRTProjectionActual = 2,
  TRTProjectionDelayed = 3,
};

@class TRTStatus;

SWIFT_CLASS_NAMED("RealTimeInformation")
@interface TRTRealTimeInformation : NSObject
@property (nonatomic, readonly, copy) NSDate * _Nullable time;
@property (nonatomic, readonly, copy) NSString * _Nullable platform;
@property (nonatomic, readonly) enum TRTProjection projection;
@property (nonatomic, readonly, strong) TRTStatus * _Nonnull status;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




SWIFT_CLASS_NAMED("ScheduledInformation")
@interface TRTScheduledInformation : NSObject
@property (nonatomic, readonly, copy) NSDate * _Nullable time;
@property (nonatomic, readonly, copy) NSString * _Nullable platform;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




SWIFT_CLASS_NAMED("Station")
@interface TRTStation : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull crsCode;
- (nonnull instancetype)initWithCrsCode:(NSString * _Nonnull)crsCode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




SWIFT_CLASS_NAMED("Status")
@interface TRTStatus : NSObject
@property (nonatomic, readonly) enum TRTStatusType type;
@property (nonatomic, readonly) BOOL arrived;
@property (nonatomic, readonly) BOOL departed;
@property (nonatomic, readonly, copy) NSString * _Nullable disruptionCode;
@property (nonatomic, readonly, copy) NSString * _Nullable disruptionReason;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



typedef SWIFT_ENUM_NAMED(NSInteger, TRTStatusType, "StatusType", closed) {
  TRTStatusTypeOnTime = 0,
  TRTStatusTypeDelayed = 1,
  TRTStatusTypeCancelled = 2,
};

@class TRTTripService;

SWIFT_CLASS_NAMED("Stop")
@interface TRTStop : NSObject
@property (nonatomic, readonly) enum TRTCallingType callingType;
@property (nonatomic, readonly, strong) TRTStation * _Nonnull station;
@property (nonatomic, readonly, strong) TRTBoardingInformation * _Nullable arrival;
@property (nonatomic, readonly, strong) TRTBoardingInformation * _Nullable departure;
@property (nonatomic, readonly, copy) NSArray<TRTTripService *> * _Nullable associatedServices;
@property (nonatomic) BOOL lastDepartedStop;
@property (nonatomic) BOOL nextArrivalStop;
@property (nonatomic) BOOL serviceAtDestination;
@property (nonatomic) BOOL serviceAtOrigin;
@property (nonatomic) BOOL serviceAtStop;
@property (nonatomic, readonly) enum TRTStatusType status;
@property (nonatomic, readonly, copy) NSString * _Nullable disruptionCode;
@property (nonatomic, readonly, copy) NSString * _Nullable disruptionReason;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




@interface TRTStop (SWIFT_EXTENSION(RealTime)) <NSCopying>
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS_NAMED("StopAtInformation")
@interface TRTStopAtInformation : NSObject
@property (nonatomic, readonly) enum TRTCallingType callingType;
@property (nonatomic, readonly, strong) TRTBoardingInformation * _Nullable boardingInformation;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




SWIFT_CLASS_NAMED("Trip")
@interface TRTTrip : NSObject
@property (nonatomic, readonly, strong) TRTTripService * _Nonnull service;
@property (nonatomic, readonly) BOOL darwinDataFeedAvailable;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



@protocol TRTTripRequestParameters;

SWIFT_CLASS_NAMED("TripRequest")
@interface TRTTripRequest : NSObject
- (nonnull instancetype)initWithBaseURL:(NSURL * _Nonnull)baseURL parameters:(id <TRTTripRequestParameters> _Nonnull)parameters OBJC_DESIGNATED_INITIALIZER;
- (NSURLSessionDataTask * _Nonnull)fetchTripWithCompletion:(void (^ _Nonnull)(TRTTrip * _Nullable, NSError * _Nullable))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL_NAMED("TripRequestParameters")
@protocol TRTTripRequestParameters
- (NSURL * _Nonnull)urlWithPreferredBaseURL:(NSURL * _Nonnull)preferredBaseURL SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS_NAMED("TripRequestExplicitParameters")
@interface TRTTripRequestExplicitParameters : NSObject <TRTTripRequestParameters>
@property (nonatomic, readonly, copy) NSString * _Nonnull trainIdentifier;
@property (nonatomic, readonly, copy) NSDate * _Nonnull date;
- (nonnull instancetype)initWithTrainIdentifier:(NSString * _Nonnull)trainIdentifier date:(NSDate * _Nonnull)date OBJC_DESIGNATED_INITIALIZER;
- (NSURL * _Nonnull)urlWithPreferredBaseURL:(NSURL * _Nonnull)preferredBaseURL SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("TripRequestImplicitParameters")
@interface TRTTripRequestImplicitParameters : NSObject <TRTTripRequestParameters>
@property (nonatomic, readonly, copy) NSURL * _Nonnull url;
- (nonnull instancetype)initWithUrl:(NSURL * _Nonnull)url OBJC_DESIGNATED_INITIALIZER;
- (NSURL * _Nonnull)urlWithPreferredBaseURL:(NSURL * _Nonnull)preferredBaseURL SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


enum TRTTripServiceAssociation : NSInteger;

SWIFT_CLASS_NAMED("TripService")
@interface TRTTripService : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull serviceOperator;
@property (nonatomic, readonly, copy) NSString * _Nonnull transportMode;
@property (nonatomic, readonly) BOOL replacementBus;
@property (nonatomic, readonly, copy) NSArray<TRTStop *> * _Nonnull stops;
@property (nonatomic, readonly) enum TRTTripServiceAssociation association;
@property (nonatomic) enum TRTTripServiceAssociation detectedAssociation;
@property (nonatomic, copy) NSArray<TRTStop *> * _Nullable commonStops;
@property (nonatomic, copy) NSArray<TRTStop *> * _Nullable leftLegStops;
@property (nonatomic, copy) NSArray<TRTStop *> * _Nullable rightLegStops;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



typedef SWIFT_ENUM_NAMED(NSInteger, TRTTripServiceAssociation, "TripServiceAssociation", closed) {
  TRTTripServiceAssociationNone = 0,
  TRTTripServiceAssociationSplit = 1,
  TRTTripServiceAssociationJoin = 2,
};

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#endif

#else
#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.0.1 effective-4.2 (swiftlang-1001.0.82.4 clang-1001.0.46.5)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="RealTime",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

enum TRTBoardType : NSInteger;
@class TRTStation;
@class TRTBoardService;
@class TRTDisruption;

SWIFT_CLASS_NAMED("Board")
@interface TRTBoard : NSObject
@property (nonatomic, readonly) enum TRTBoardType type;
@property (nonatomic, readonly, strong) TRTStation * _Nonnull station;
@property (nonatomic, readonly, copy) NSArray<TRTBoardService *> * _Nonnull services;
@property (nonatomic, readonly, copy) NSDate * _Nonnull lastUpdate;
@property (nonatomic, readonly) BOOL darwinDataFeedAvailable;
@property (nonatomic, readonly, copy) NSURL * _Nonnull earlierServicesURL;
@property (nonatomic, readonly, copy) NSURL * _Nonnull laterServicesURL;
@property (nonatomic, readonly, copy) NSArray<TRTDisruption *> * _Nullable disruptions;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



@protocol TRTBoardRequestParameters;
@class NSURLSessionDataTask;

SWIFT_CLASS_NAMED("BoardRequest")
@interface TRTBoardRequest : NSObject
- (nonnull instancetype)initWithBaseURL:(NSURL * _Nonnull)baseURL parameters:(id <TRTBoardRequestParameters> _Nonnull)parameters OBJC_DESIGNATED_INITIALIZER;
- (NSURLSessionDataTask * _Nonnull)fetchBoardWithCompletion:(void (^ _Nonnull)(TRTBoard * _Nullable, NSError * _Nullable))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL_NAMED("BoardRequestParameters")
@protocol TRTBoardRequestParameters
@property (nonatomic, readonly) enum TRTBoardType type;
@property (nonatomic, readonly, strong) TRTStation * _Nonnull station;
- (NSURL * _Nonnull)urlWithPreferredBaseURL:(NSURL * _Nonnull)preferredBaseURL SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS_NAMED("BoardRequestExplicitParameters")
@interface TRTBoardRequestExplicitParameters : NSObject <TRTBoardRequestParameters>
@property (nonatomic, readonly) enum TRTBoardType type;
@property (nonatomic, readonly, strong) TRTStation * _Nonnull station;
- (nonnull instancetype)initWithType:(enum TRTBoardType)type station:(TRTStation * _Nonnull)station stopAtStation:(TRTStation * _Nullable)stopAtStation time:(NSDate * _Nullable)time OBJC_DESIGNATED_INITIALIZER;
- (NSURL * _Nonnull)urlWithPreferredBaseURL:(NSURL * _Nonnull)preferredBaseURL SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("BoardRequestImplicitParameters")
@interface TRTBoardRequestImplicitParameters : NSObject <TRTBoardRequestParameters>
@property (nonatomic, readonly) enum TRTBoardType type;
@property (nonatomic, readonly, strong) TRTStation * _Nonnull station;
- (nonnull instancetype)initWithType:(enum TRTBoardType)type station:(TRTStation * _Nonnull)station url:(NSURL * _Nonnull)url OBJC_DESIGNATED_INITIALIZER;
- (NSURL * _Nonnull)urlWithPreferredBaseURL:(NSURL * _Nonnull)preferredBaseURL SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


enum TRTCallingType : NSInteger;
@class TRTBoardingInformation;
@class TRTStopAtInformation;
enum TRTStatusType : NSInteger;

SWIFT_CLASS_NAMED("BoardService")
@interface TRTBoardService : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull identifier;
@property (nonatomic, readonly, copy) NSString * _Nonnull serviceOperator;
@property (nonatomic, readonly, copy) NSString * _Nonnull transportMode;
@property (nonatomic, readonly) enum TRTCallingType callingType;
@property (nonatomic, readonly, copy) NSArray<TRTStation *> * _Nonnull stations;
@property (nonatomic, readonly, copy) NSString * _Nullable via;
@property (nonatomic, readonly, strong) TRTBoardingInformation * _Nonnull boardingInformation;
@property (nonatomic, readonly, strong) TRTStopAtInformation * _Nullable stopAtInformation;
@property (nonatomic, readonly, copy) NSURL * _Nonnull tripURL;
@property (nonatomic, readonly) BOOL circularRoute;
@property (nonatomic, readonly) BOOL splits;
@property (nonatomic, readonly) BOOL joins;
@property (nonatomic, readonly) enum TRTStatusType status;
@property (nonatomic, readonly, copy) NSString * _Nullable disruptionCode;
@property (nonatomic, readonly, copy) NSString * _Nullable disruptionReason;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




@interface TRTBoardService (SWIFT_EXTENSION(RealTime))
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) NSUInteger hash;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, TRTBoardType, "BoardType", closed) {
  TRTBoardTypeDepartures = 0,
  TRTBoardTypeArrivals = 1,
};

@class TRTScheduledInformation;
@class TRTRealTimeInformation;

SWIFT_CLASS_NAMED("BoardingInformation")
@interface TRTBoardingInformation : NSObject
@property (nonatomic, readonly, strong) TRTScheduledInformation * _Nullable scheduled;
@property (nonatomic, strong) TRTRealTimeInformation * _Nullable realTime;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



typedef SWIFT_ENUM_NAMED(NSInteger, TRTCallingType, "CallingType", closed) {
  TRTCallingTypePickUp = 0,
  TRTCallingTypeNormal = 1,
  TRTCallingTypePassing = 2,
  TRTCallingTypeSetDown = 3,
  TRTCallingTypeRequest = 4,
};




SWIFT_CLASS_NAMED("Disruption")
@interface TRTDisruption : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull category;
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
@property (nonatomic, readonly, copy) NSString * _Nonnull severity;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



typedef SWIFT_ENUM_NAMED(NSInteger, TRTErrorCode, "ErrorCode", closed) {
  TRTErrorCodeUnknown = 0,
  TRTErrorCodeInvalidRequest = 1,
  TRTErrorCodeInvalidResponse = 2,
  TRTErrorCodeInternalError = 3,
  TRTErrorCodeNotFound = 4,
  TRTErrorCodeRequestTimedOut = 5,
  TRTErrorCodeInvalidParameter = 6,
  TRTErrorCodeInvalidParameterValue = 7,
};



typedef SWIFT_ENUM_NAMED(NSInteger, TRTProjection, "Projection", closed) {
  TRTProjectionNone = 0,
  TRTProjectionEstimated = 1,
  TRTProjectionActual = 2,
  TRTProjectionDelayed = 3,
};

@class TRTStatus;

SWIFT_CLASS_NAMED("RealTimeInformation")
@interface TRTRealTimeInformation : NSObject
@property (nonatomic, readonly, copy) NSDate * _Nullable time;
@property (nonatomic, readonly, copy) NSString * _Nullable platform;
@property (nonatomic, readonly) enum TRTProjection projection;
@property (nonatomic, readonly, strong) TRTStatus * _Nonnull status;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




SWIFT_CLASS_NAMED("ScheduledInformation")
@interface TRTScheduledInformation : NSObject
@property (nonatomic, readonly, copy) NSDate * _Nullable time;
@property (nonatomic, readonly, copy) NSString * _Nullable platform;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




SWIFT_CLASS_NAMED("Station")
@interface TRTStation : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull crsCode;
- (nonnull instancetype)initWithCrsCode:(NSString * _Nonnull)crsCode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




SWIFT_CLASS_NAMED("Status")
@interface TRTStatus : NSObject
@property (nonatomic, readonly) enum TRTStatusType type;
@property (nonatomic, readonly) BOOL arrived;
@property (nonatomic, readonly) BOOL departed;
@property (nonatomic, readonly, copy) NSString * _Nullable disruptionCode;
@property (nonatomic, readonly, copy) NSString * _Nullable disruptionReason;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



typedef SWIFT_ENUM_NAMED(NSInteger, TRTStatusType, "StatusType", closed) {
  TRTStatusTypeOnTime = 0,
  TRTStatusTypeDelayed = 1,
  TRTStatusTypeCancelled = 2,
};

@class TRTTripService;

SWIFT_CLASS_NAMED("Stop")
@interface TRTStop : NSObject
@property (nonatomic, readonly) enum TRTCallingType callingType;
@property (nonatomic, readonly, strong) TRTStation * _Nonnull station;
@property (nonatomic, readonly, strong) TRTBoardingInformation * _Nullable arrival;
@property (nonatomic, readonly, strong) TRTBoardingInformation * _Nullable departure;
@property (nonatomic, readonly, copy) NSArray<TRTTripService *> * _Nullable associatedServices;
@property (nonatomic) BOOL lastDepartedStop;
@property (nonatomic) BOOL nextArrivalStop;
@property (nonatomic) BOOL serviceAtDestination;
@property (nonatomic) BOOL serviceAtOrigin;
@property (nonatomic) BOOL serviceAtStop;
@property (nonatomic, readonly) enum TRTStatusType status;
@property (nonatomic, readonly, copy) NSString * _Nullable disruptionCode;
@property (nonatomic, readonly, copy) NSString * _Nullable disruptionReason;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




@interface TRTStop (SWIFT_EXTENSION(RealTime)) <NSCopying>
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS_NAMED("StopAtInformation")
@interface TRTStopAtInformation : NSObject
@property (nonatomic, readonly) enum TRTCallingType callingType;
@property (nonatomic, readonly, strong) TRTBoardingInformation * _Nullable boardingInformation;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




SWIFT_CLASS_NAMED("Trip")
@interface TRTTrip : NSObject
@property (nonatomic, readonly, strong) TRTTripService * _Nonnull service;
@property (nonatomic, readonly) BOOL darwinDataFeedAvailable;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



@protocol TRTTripRequestParameters;

SWIFT_CLASS_NAMED("TripRequest")
@interface TRTTripRequest : NSObject
- (nonnull instancetype)initWithBaseURL:(NSURL * _Nonnull)baseURL parameters:(id <TRTTripRequestParameters> _Nonnull)parameters OBJC_DESIGNATED_INITIALIZER;
- (NSURLSessionDataTask * _Nonnull)fetchTripWithCompletion:(void (^ _Nonnull)(TRTTrip * _Nullable, NSError * _Nullable))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL_NAMED("TripRequestParameters")
@protocol TRTTripRequestParameters
- (NSURL * _Nonnull)urlWithPreferredBaseURL:(NSURL * _Nonnull)preferredBaseURL SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS_NAMED("TripRequestExplicitParameters")
@interface TRTTripRequestExplicitParameters : NSObject <TRTTripRequestParameters>
@property (nonatomic, readonly, copy) NSString * _Nonnull trainIdentifier;
@property (nonatomic, readonly, copy) NSDate * _Nonnull date;
- (nonnull instancetype)initWithTrainIdentifier:(NSString * _Nonnull)trainIdentifier date:(NSDate * _Nonnull)date OBJC_DESIGNATED_INITIALIZER;
- (NSURL * _Nonnull)urlWithPreferredBaseURL:(NSURL * _Nonnull)preferredBaseURL SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("TripRequestImplicitParameters")
@interface TRTTripRequestImplicitParameters : NSObject <TRTTripRequestParameters>
@property (nonatomic, readonly, copy) NSURL * _Nonnull url;
- (nonnull instancetype)initWithUrl:(NSURL * _Nonnull)url OBJC_DESIGNATED_INITIALIZER;
- (NSURL * _Nonnull)urlWithPreferredBaseURL:(NSURL * _Nonnull)preferredBaseURL SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


enum TRTTripServiceAssociation : NSInteger;

SWIFT_CLASS_NAMED("TripService")
@interface TRTTripService : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull serviceOperator;
@property (nonatomic, readonly, copy) NSString * _Nonnull transportMode;
@property (nonatomic, readonly) BOOL replacementBus;
@property (nonatomic, readonly, copy) NSArray<TRTStop *> * _Nonnull stops;
@property (nonatomic, readonly) enum TRTTripServiceAssociation association;
@property (nonatomic) enum TRTTripServiceAssociation detectedAssociation;
@property (nonatomic, copy) NSArray<TRTStop *> * _Nullable commonStops;
@property (nonatomic, copy) NSArray<TRTStop *> * _Nullable leftLegStops;
@property (nonatomic, copy) NSArray<TRTStop *> * _Nullable rightLegStops;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



typedef SWIFT_ENUM_NAMED(NSInteger, TRTTripServiceAssociation, "TripServiceAssociation", closed) {
  TRTTripServiceAssociationNone = 0,
  TRTTripServiceAssociationSplit = 1,
  TRTTripServiceAssociationJoin = 2,
};

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#elif defined(__ARM_ARCH_7A__) && __ARM_ARCH_7A__
// Generated by Apple Swift version 5.0.1 effective-4.2 (swiftlang-1001.0.82.4 clang-1001.0.46.5)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="RealTime",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

enum TRTBoardType : NSInteger;
@class TRTStation;
@class TRTBoardService;
@class TRTDisruption;

SWIFT_CLASS_NAMED("Board")
@interface TRTBoard : NSObject
@property (nonatomic, readonly) enum TRTBoardType type;
@property (nonatomic, readonly, strong) TRTStation * _Nonnull station;
@property (nonatomic, readonly, copy) NSArray<TRTBoardService *> * _Nonnull services;
@property (nonatomic, readonly, copy) NSDate * _Nonnull lastUpdate;
@property (nonatomic, readonly) BOOL darwinDataFeedAvailable;
@property (nonatomic, readonly, copy) NSURL * _Nonnull earlierServicesURL;
@property (nonatomic, readonly, copy) NSURL * _Nonnull laterServicesURL;
@property (nonatomic, readonly, copy) NSArray<TRTDisruption *> * _Nullable disruptions;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



@protocol TRTBoardRequestParameters;
@class NSURLSessionDataTask;

SWIFT_CLASS_NAMED("BoardRequest")
@interface TRTBoardRequest : NSObject
- (nonnull instancetype)initWithBaseURL:(NSURL * _Nonnull)baseURL parameters:(id <TRTBoardRequestParameters> _Nonnull)parameters OBJC_DESIGNATED_INITIALIZER;
- (NSURLSessionDataTask * _Nonnull)fetchBoardWithCompletion:(void (^ _Nonnull)(TRTBoard * _Nullable, NSError * _Nullable))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL_NAMED("BoardRequestParameters")
@protocol TRTBoardRequestParameters
@property (nonatomic, readonly) enum TRTBoardType type;
@property (nonatomic, readonly, strong) TRTStation * _Nonnull station;
- (NSURL * _Nonnull)urlWithPreferredBaseURL:(NSURL * _Nonnull)preferredBaseURL SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS_NAMED("BoardRequestExplicitParameters")
@interface TRTBoardRequestExplicitParameters : NSObject <TRTBoardRequestParameters>
@property (nonatomic, readonly) enum TRTBoardType type;
@property (nonatomic, readonly, strong) TRTStation * _Nonnull station;
- (nonnull instancetype)initWithType:(enum TRTBoardType)type station:(TRTStation * _Nonnull)station stopAtStation:(TRTStation * _Nullable)stopAtStation time:(NSDate * _Nullable)time OBJC_DESIGNATED_INITIALIZER;
- (NSURL * _Nonnull)urlWithPreferredBaseURL:(NSURL * _Nonnull)preferredBaseURL SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("BoardRequestImplicitParameters")
@interface TRTBoardRequestImplicitParameters : NSObject <TRTBoardRequestParameters>
@property (nonatomic, readonly) enum TRTBoardType type;
@property (nonatomic, readonly, strong) TRTStation * _Nonnull station;
- (nonnull instancetype)initWithType:(enum TRTBoardType)type station:(TRTStation * _Nonnull)station url:(NSURL * _Nonnull)url OBJC_DESIGNATED_INITIALIZER;
- (NSURL * _Nonnull)urlWithPreferredBaseURL:(NSURL * _Nonnull)preferredBaseURL SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


enum TRTCallingType : NSInteger;
@class TRTBoardingInformation;
@class TRTStopAtInformation;
enum TRTStatusType : NSInteger;

SWIFT_CLASS_NAMED("BoardService")
@interface TRTBoardService : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull identifier;
@property (nonatomic, readonly, copy) NSString * _Nonnull serviceOperator;
@property (nonatomic, readonly, copy) NSString * _Nonnull transportMode;
@property (nonatomic, readonly) enum TRTCallingType callingType;
@property (nonatomic, readonly, copy) NSArray<TRTStation *> * _Nonnull stations;
@property (nonatomic, readonly, copy) NSString * _Nullable via;
@property (nonatomic, readonly, strong) TRTBoardingInformation * _Nonnull boardingInformation;
@property (nonatomic, readonly, strong) TRTStopAtInformation * _Nullable stopAtInformation;
@property (nonatomic, readonly, copy) NSURL * _Nonnull tripURL;
@property (nonatomic, readonly) BOOL circularRoute;
@property (nonatomic, readonly) BOOL splits;
@property (nonatomic, readonly) BOOL joins;
@property (nonatomic, readonly) enum TRTStatusType status;
@property (nonatomic, readonly, copy) NSString * _Nullable disruptionCode;
@property (nonatomic, readonly, copy) NSString * _Nullable disruptionReason;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




@interface TRTBoardService (SWIFT_EXTENSION(RealTime))
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) NSUInteger hash;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, TRTBoardType, "BoardType", closed) {
  TRTBoardTypeDepartures = 0,
  TRTBoardTypeArrivals = 1,
};

@class TRTScheduledInformation;
@class TRTRealTimeInformation;

SWIFT_CLASS_NAMED("BoardingInformation")
@interface TRTBoardingInformation : NSObject
@property (nonatomic, readonly, strong) TRTScheduledInformation * _Nullable scheduled;
@property (nonatomic, strong) TRTRealTimeInformation * _Nullable realTime;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



typedef SWIFT_ENUM_NAMED(NSInteger, TRTCallingType, "CallingType", closed) {
  TRTCallingTypePickUp = 0,
  TRTCallingTypeNormal = 1,
  TRTCallingTypePassing = 2,
  TRTCallingTypeSetDown = 3,
  TRTCallingTypeRequest = 4,
};




SWIFT_CLASS_NAMED("Disruption")
@interface TRTDisruption : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull category;
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
@property (nonatomic, readonly, copy) NSString * _Nonnull severity;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



typedef SWIFT_ENUM_NAMED(NSInteger, TRTErrorCode, "ErrorCode", closed) {
  TRTErrorCodeUnknown = 0,
  TRTErrorCodeInvalidRequest = 1,
  TRTErrorCodeInvalidResponse = 2,
  TRTErrorCodeInternalError = 3,
  TRTErrorCodeNotFound = 4,
  TRTErrorCodeRequestTimedOut = 5,
  TRTErrorCodeInvalidParameter = 6,
  TRTErrorCodeInvalidParameterValue = 7,
};



typedef SWIFT_ENUM_NAMED(NSInteger, TRTProjection, "Projection", closed) {
  TRTProjectionNone = 0,
  TRTProjectionEstimated = 1,
  TRTProjectionActual = 2,
  TRTProjectionDelayed = 3,
};

@class TRTStatus;

SWIFT_CLASS_NAMED("RealTimeInformation")
@interface TRTRealTimeInformation : NSObject
@property (nonatomic, readonly, copy) NSDate * _Nullable time;
@property (nonatomic, readonly, copy) NSString * _Nullable platform;
@property (nonatomic, readonly) enum TRTProjection projection;
@property (nonatomic, readonly, strong) TRTStatus * _Nonnull status;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




SWIFT_CLASS_NAMED("ScheduledInformation")
@interface TRTScheduledInformation : NSObject
@property (nonatomic, readonly, copy) NSDate * _Nullable time;
@property (nonatomic, readonly, copy) NSString * _Nullable platform;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




SWIFT_CLASS_NAMED("Station")
@interface TRTStation : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull crsCode;
- (nonnull instancetype)initWithCrsCode:(NSString * _Nonnull)crsCode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




SWIFT_CLASS_NAMED("Status")
@interface TRTStatus : NSObject
@property (nonatomic, readonly) enum TRTStatusType type;
@property (nonatomic, readonly) BOOL arrived;
@property (nonatomic, readonly) BOOL departed;
@property (nonatomic, readonly, copy) NSString * _Nullable disruptionCode;
@property (nonatomic, readonly, copy) NSString * _Nullable disruptionReason;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



typedef SWIFT_ENUM_NAMED(NSInteger, TRTStatusType, "StatusType", closed) {
  TRTStatusTypeOnTime = 0,
  TRTStatusTypeDelayed = 1,
  TRTStatusTypeCancelled = 2,
};

@class TRTTripService;

SWIFT_CLASS_NAMED("Stop")
@interface TRTStop : NSObject
@property (nonatomic, readonly) enum TRTCallingType callingType;
@property (nonatomic, readonly, strong) TRTStation * _Nonnull station;
@property (nonatomic, readonly, strong) TRTBoardingInformation * _Nullable arrival;
@property (nonatomic, readonly, strong) TRTBoardingInformation * _Nullable departure;
@property (nonatomic, readonly, copy) NSArray<TRTTripService *> * _Nullable associatedServices;
@property (nonatomic) BOOL lastDepartedStop;
@property (nonatomic) BOOL nextArrivalStop;
@property (nonatomic) BOOL serviceAtDestination;
@property (nonatomic) BOOL serviceAtOrigin;
@property (nonatomic) BOOL serviceAtStop;
@property (nonatomic, readonly) enum TRTStatusType status;
@property (nonatomic, readonly, copy) NSString * _Nullable disruptionCode;
@property (nonatomic, readonly, copy) NSString * _Nullable disruptionReason;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




@interface TRTStop (SWIFT_EXTENSION(RealTime)) <NSCopying>
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS_NAMED("StopAtInformation")
@interface TRTStopAtInformation : NSObject
@property (nonatomic, readonly) enum TRTCallingType callingType;
@property (nonatomic, readonly, strong) TRTBoardingInformation * _Nullable boardingInformation;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




SWIFT_CLASS_NAMED("Trip")
@interface TRTTrip : NSObject
@property (nonatomic, readonly, strong) TRTTripService * _Nonnull service;
@property (nonatomic, readonly) BOOL darwinDataFeedAvailable;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



@protocol TRTTripRequestParameters;

SWIFT_CLASS_NAMED("TripRequest")
@interface TRTTripRequest : NSObject
- (nonnull instancetype)initWithBaseURL:(NSURL * _Nonnull)baseURL parameters:(id <TRTTripRequestParameters> _Nonnull)parameters OBJC_DESIGNATED_INITIALIZER;
- (NSURLSessionDataTask * _Nonnull)fetchTripWithCompletion:(void (^ _Nonnull)(TRTTrip * _Nullable, NSError * _Nullable))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL_NAMED("TripRequestParameters")
@protocol TRTTripRequestParameters
- (NSURL * _Nonnull)urlWithPreferredBaseURL:(NSURL * _Nonnull)preferredBaseURL SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS_NAMED("TripRequestExplicitParameters")
@interface TRTTripRequestExplicitParameters : NSObject <TRTTripRequestParameters>
@property (nonatomic, readonly, copy) NSString * _Nonnull trainIdentifier;
@property (nonatomic, readonly, copy) NSDate * _Nonnull date;
- (nonnull instancetype)initWithTrainIdentifier:(NSString * _Nonnull)trainIdentifier date:(NSDate * _Nonnull)date OBJC_DESIGNATED_INITIALIZER;
- (NSURL * _Nonnull)urlWithPreferredBaseURL:(NSURL * _Nonnull)preferredBaseURL SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("TripRequestImplicitParameters")
@interface TRTTripRequestImplicitParameters : NSObject <TRTTripRequestParameters>
@property (nonatomic, readonly, copy) NSURL * _Nonnull url;
- (nonnull instancetype)initWithUrl:(NSURL * _Nonnull)url OBJC_DESIGNATED_INITIALIZER;
- (NSURL * _Nonnull)urlWithPreferredBaseURL:(NSURL * _Nonnull)preferredBaseURL SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


enum TRTTripServiceAssociation : NSInteger;

SWIFT_CLASS_NAMED("TripService")
@interface TRTTripService : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull serviceOperator;
@property (nonatomic, readonly, copy) NSString * _Nonnull transportMode;
@property (nonatomic, readonly) BOOL replacementBus;
@property (nonatomic, readonly, copy) NSArray<TRTStop *> * _Nonnull stops;
@property (nonatomic, readonly) enum TRTTripServiceAssociation association;
@property (nonatomic) enum TRTTripServiceAssociation detectedAssociation;
@property (nonatomic, copy) NSArray<TRTStop *> * _Nullable commonStops;
@property (nonatomic, copy) NSArray<TRTStop *> * _Nullable leftLegStops;
@property (nonatomic, copy) NSArray<TRTStop *> * _Nullable rightLegStops;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



typedef SWIFT_ENUM_NAMED(NSInteger, TRTTripServiceAssociation, "TripServiceAssociation", closed) {
  TRTTripServiceAssociationNone = 0,
  TRTTripServiceAssociationSplit = 1,
  TRTTripServiceAssociationJoin = 2,
};

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#endif

#endif
